# Generated by Django 3.1 on 2023-12-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsUsers', '0002_normaluser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='FName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='LName',
            new_name='LastName',
        ),
    ]
