# Generated by Django 3.1 on 2023-12-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20231209_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image6',
        ),
    ]
