# Generated by Django 3.1 on 2023-12-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_auto_20231209_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image5',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image6',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
    ]
