# Generated by Django 3.1 on 2023-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_auto_20231210_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
