# Generated by Django 3.1 on 2023-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imageHeader',
            field=models.ImageField(null=True, upload_to='Car_images/'),
        ),
    ]
