# Generated by Django 3.1 on 2023-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmCar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
