# Generated by Django 3.1 on 2023-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmCar', '0002_auto_20231214_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
