# Generated by Django 3.1 on 2023-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmCar', '0006_auto_20231218_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
