# Generated by Django 3.1 on 2023-12-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmCar', '0007_auto_20231218_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Date',
        ),
    ]
