# Generated by Django 3.1 on 2023-12-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmCar', '0008_remove_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
